
USE EVENTOSDB;
GO

-- Creación de usuarios y asignación de permisos totales
CREATE USER HilciasC WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER HilciasC;

CREATE USER AxellT WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER AxellT;

CREATE USER JuanP WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER JuanP;

CREATE USER AndreaI WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER AndreaI;

CREATE USER KevinB WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER KevinB;

CREATE USER FreddyR WITHOUT LOGIN;
ALTER ROLE db_owner ADD MEMBER FreddyR;
